gem 'squash_ruby', '>= 1.2.0', require: 'squash/ruby'
gem 'squash_rails', require: 'squash/rails'
gem 'squash_ios_symbolicator', require: 'squash/symbolicator'
gem 'squash_javascript', require: 'squash/javascript'
gem 'squash_java', require: 'squash/java'
