development:
  adapter: postgresql
  encoding: utf8
  hostname:
  username: squash
  password:
  database: squash_development

test:
  adapter: postgresql
  encoding: utf8
  hostname:
  username: squash
  password:
  database: squash_test

production:
  adapter: postgresql
  encoding: utf8
  hostname:
  username: squash
  password:
  database: squash_production
  pool: 30
